DELETE FROM connections;
DELETE FROM entities;

INSERT INTO connections_abstraction (from_name, from_type, to_name, to_type)
VALUES
--- Sources from "Debunking transphobia" and Kehrääjä and Erin Reed
--- [@jasperdasper2025; @reed2023; @reed2024; @reed2025; @reed2025b; @genderanalysis2024; @kehraaja2021]

('Time To Think', 'pseudoscientific theory', 'Susan Evans', 'person'),
('Time To Think', 'pseudoscientific theory', 'Marcus Evans', 'person'),
('Susan Evans', 'person', 'Marcus Evans', 'person'),

('Time To Think', 'pseudoscientific theory', 'Hannah Barnes', 'person'),
('Time To Think', 'pseudoscientific theory', 'Az Hakeem', 'person'),
('Time To Think', 'pseudoscientific theory', 'David Bell', 'person'),
('Time To Think', 'pseudoscientific theory', 'Anna Hutchinson', 'person'),
('Time To Think', 'pseudoscientific theory', 'Stephanie Davies Arai', 'person'),
('Time To Think', 'group', 'Melissa Midgen', 'person'),
('Time To Think', 'group', 'Kirsty Entwistle', 'person'),
('Time To Think', 'group', 'Anastassis Spiliadis', 'person'),

('SEGM', 'group', 'Hannah Barnes', 'person'),
('SEGM', 'group', 'Julia Mason', 'person'),
('SEGM', 'group', 'Zhenya Abbruzzese', 'person'),
('SEGM', 'group', 'Michael Absoud', 'person'),
('SEGM', 'group', 'Julie Alderson', 'person'),
('SEGM', 'group', 'Erica Anderson', 'person'),
('SEGM', 'group', 'Sallie Baxendale', 'person'),
('SEGM', 'group', 'Mikael Scott Bjerkeli', 'person'),
('SEGM', 'group', 'Leslie Elliott Boyce', 'person'),
('SEGM', 'group', 'Joe Burgo', 'person'),
('SEGM', 'group', 'Richard Byng', 'person'),
('SEGM', 'group', 'Alex Byrne', 'person'),
('SEGM', 'group', 'Raisa Cacciatore', 'person'),
('SEGM', 'group', 'Alison Clayton', 'person'),
('SEGM', 'group', 'Patricia Constantinian', 'person'),
('SEGM', 'group', 'Roberto D’Angelo', 'person'),
('SEGM', 'group', 'Stephanie Davies-Arai', 'person'),
('SEGM', 'group', 'Lisa Duval', 'person'),
('SEGM', 'group', 'Lisa Marchiano', 'person'),
('SEGM', 'group', 'Foteini Ferenidou', 'person'),
('SEGM', 'group', 'Sophie Frost', 'person'),
('SEGM', 'group', 'Paul Garcia-Ryan', 'person'),
('SEGM', 'group', 'Shlomit Gorin', 'person'),
('SEGM', 'group', 'Andrew Hartz', 'person'),
('SEGM', 'group', 'Anna Hutchinson', 'person'),
('SEGM', 'group', 'Amita Jassi', 'person'),
('SEGM', 'group', 'Lucy Johnstone', 'person'),
('SEGM', 'group', 'Kristopher Kaliebe', 'person'),
('SEGM', 'group', 'Riittakerttu Kalttiala', 'person'),
('SEGM', 'group', 'Beryl Koener', 'person'),
('SEGM', 'group', 'Alexander Korte', 'person'),
('SEGM', 'group', 'Alexandre Ledrait', 'person'),
('SEGM', 'group', 'Lisa Littman', 'person'),
('SEGM', 'group', 'Sarah Mittermaier', 'person'),
('SEGM', 'group', 'Dwight Panozzo', 'person'),
('SEGM', 'group', 'Maja Radobuliac', 'person'),
('SEGM', 'group', 'Jamie Reed', 'person'),
('SEGM', 'group', 'Patrick Ryan', 'person'),
('SEGM', 'group', 'Jilles Smids', 'person'),
('SEGM', 'group', 'Anastassis Spiliadis', 'person'),
('SEGM', 'group', 'Richard Stephens', 'person'),
('SEGM', 'group', 'Stephen Beck', 'person'),
('SEGM', 'group', 'Artemis Tsitsika', 'person'),
('SEGM', 'group', 'Samuel Veissière', 'person'),
('SEGM', 'group', 'Anne Wæhre', 'person'),
('SEGM', 'group', 'Kathryn Webb', 'person'),
('SEGM', 'group', 'Yuan (Ray) Zhang', 'person'),
('SEGM', 'group', 'Kenneth Zucker', 'person'),
('SEGM', 'group', 'Kathleen Goonan', 'person'),
('SEGM', 'group', 'Sasha Ayad', 'person'),
('SEGM', 'group', 'William Malone', 'person'),
('SEGM', 'group', 'Michael Biggs', 'person'),
('SEGM', 'group', 'Marcus Evans', 'person'),

('ACPEDS', 'group', 'Michael Laidlaw', 'person'),
('ACPEDS', 'group', 'Paul Hruz', 'person'),
('ACPEDS', 'group', 'Quentin Van Meter', 'person'),
('ACPEDS', 'group', 'Andre Van Mol', 'person'),
('ACPEDS', 'group', 'Michelle Cretella', 'person'),

('Do No Harm', 'group', 'ACPEDS', 'group'),
('Do No Harm', 'group', 'Genspect', 'group'),

('ADF', 'group', 'Minnesota Family Council', 'group'),

('Sharon Beck', 'person', 'Stephen Beck', 'person'),
('Sharon Beck', 'person', 'Cardinal Support Network', 'group'),
('Sharon Beck', 'person', 'Parents of ROGD Kids', 'group'),

('Family Policy Alliance', 'group', 'Minnesota Family Council', 'group'),

('Parents Resource Guide', 'pseuoscientific theory', 'Heritage Foundation', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'ACPEDS', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'Family Policy Alliance', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'Heritage Foundation', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'WOLF', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'Parents of ROGD Kids', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'Michelle Crettella', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'Michael Laidlaw', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'Susan Bradley', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'Sasha Ayad', 'group'),
('Parents Resource Guide', 'pseuoscientific theory', 'William Malone', 'group'),

('Family Resarch Council', 'group', 'George Rekers', 'person'),
('Family Resarch Council', 'group', 'Tony Perkins', 'person'),
('Family Resarch Council', 'group', 'Minnesota Family Council', 'group'),

('ATSCI (NARTH)', 'group', 'Michelle Cretella', 'person'),
('ATSCI (NARTH)', 'group', 'George Rekers', 'person'),

('1557 Affortable Care Act', 'pseuoscientific theory', 'Michelle Cretella', 'person'),
('1557 Affortable Care Act', 'pseuoscientific theory', 'Quentin Van Meter', 'person'),
('1557 Affortable Care Act', 'pseuoscientific theory', 'Paul McHugh', 'person'),
('1557 Affortable Care Act', 'pseuoscientific theory', 'Paul Hruz', 'person'),
('1557 Affortable Care Act', 'pseuoscientific theory', 'Susan Bradley', 'person'),
('1557 Affortable Care Act', 'pseuoscientific theory', 'Michael Bailey', 'person'),
('1557 Affortable Care Act', 'pseuoscientific theory', 'Laura Haynes', 'person'),
('1557 Affortable Care Act', 'pseuoscientific theory', 'Tony Perkins', 'person'),

('Kelsey Coalition', 'defunct', 'Heritage Foundation', 'group'),
('Kelsey Coalition', 'defunct', 'Michael Laidlaw', 'person'),

('Michael Laidlaw', 'person', 'William Malone', 'person'),
('Michael Laidlaw', 'person', 'Heritage Foundation', 'group'),


('Helen Joyce', 'person', 'Jennifer Bilek', 'person'),
('Helen Joyce', 'person', 'Peter Boghossian', 'person'),
('Helen Joyce', 'person', 'Sex Matters', 'group'),

('Sex Matters', 'group', 'Jo Bartosch', 'person'),
('Sex Matters', 'group', 'Maya Forstater', 'person'),

('ROGD', 'pseudoscientific theory', 'Lisa Littman', 'person'),
('4THWAWENOW', 'group', 'Lisa Littman', 'person'),
('Parents of ROGD Kids', 'group', 'Lisa Littman', 'person'),
('Transgender Trend', 'group', 'Lisa Littman', 'person'),
('Transgender Trend', 'group', 'Stephanie Davies Arai', 'person'),

('CAN-SG', 'group', 'Anna Hutchinson', 'person'),
('CAN-SG', 'group', 'Az Hakeem', 'person'),
('CAN-SG', 'group', 'Stella O’Malley', 'person'),
('CAN-SG', 'group', 'Robert Withers', 'person'),

('LGB Alliance', 'group', 'Az Hakeem', 'person'),
('LGB Alliance', 'group', 'Kathleen Stock', 'person'),
('LGB Alliance', 'group', 'Bev Jackson', 'person'),
('LGB Alliance', 'group', 'Allison Bailey', 'person'),
('LGB Alliance', 'group', 'Graham Linehan', 'person'),
('LGB Alliance', 'group', 'Malcolm Clark', 'person'),

('Heritage Foundation', 'group', 'Bev Jackson', 'person'),

('Genspect', 'group', 'Stella O’Malley', 'person'),
('Genspect', 'group', 'Az Hakeem', 'person'),
('Genspect', 'group', 'Sasha Ayad', 'person'),
('Genspect', 'group', 'Abigail Shrier', 'person'),
('Genspect', 'group', 'Lisa Littman', 'person'),
('Genspect', 'group', 'Julia Mason', 'person'),
('Genspect', 'group', 'Kathleen Goonan', 'person'),
('Genspect', 'group', 'Lisa Marchiano', 'person'),

('Gender: A Wider Lens', 'group', 'Stella O’Malley', 'person'),
('Gender: A Wider Lens', 'group', 'Sasha Ayad', 'person'),
('Gender: A Wider Lens', 'group', 'Kathleen Stock', 'person'),
('Gender: A Wider Lens', 'group', 'Peeter Boghossian', 'person'),
('Gender: A Wider Lens', 'group', 'Az Hakeem', 'person'),
('Gender: A Wider Lens', 'group', 'Kathleen Goonan', 'person'),
('Gender: A Wider Lens', 'group', 'Susan Bradley', 'person'),
('Gender: A Wider Lens', 'group', 'James Cantor', 'person'),
('Gender: A Wider Lens', 'group', 'Riittakerttu Kalttiala', 'person'),
('Gender: A Wider Lens', 'group', 'Kenneth Zucker', 'person'),
('Gender: A Wider Lens', 'group', 'Peter Boghossian', 'person'),

('GD-Working Group', 'defunct', 'Lisa Marchiano', 'person'),
('GD-Working Group', 'defunct', 'Stella O’Malley', 'person'),
('GD-Working Group', 'defunct', 'Sasha Ayad', 'person'),
('GD-Working Group', 'defunct', 'Anastassis Spiliadis', 'person'),
('GD-Working Group', 'defunct', 'Robert Withers', 'person'),
('GD-Working Group', 'defunct', 'Roberto D’Angelo', 'person'),
('GD-Working Group', 'defunct', 'Michael Bailey', 'person'),
('GD-Working Group', 'defunct', 'Ray Blanchard', 'person'),
('GD-Working Group', 'defunct', 'Susan Bradley', 'person'),
('GD-Working Group', 'defunct', 'James Cantor', 'person'),
('GD-Working Group', 'defunct', 'Michael Laidlaw', 'person'),
('GD-Working Group', 'defunct', 'Kenneth Zucker', 'person'),

('Therapy First', 'group', 'Lisa Marchiano', 'person'),
('GETA', 'defunct', 'Lisa Marchiano', 'person'),
('GETA', 'defunct', 'Stella O’Malley', 'person'),
('GETA', 'defunct', 'Sahsa Ayad', 'person'),
('GETA', 'defunct', 'Therapy First', 'group'),

('IATDD', 'defunct', 'Susan Evans', 'person'),
('IATDD', 'defunct', 'Roberto D’Angelo', 'person'),
('IATDD', 'defunct', 'Robert Withers', 'person'),

('IATDD', 'defunct', 'Lisa Marchiano', 'person'),
('IATDD', 'defunct', 'Stella O’Malley', 'person'),
('IATDD', 'defunct', 'Sahsa Ayad', 'person'),
('IATDD', 'group', 'Kirsty Entwistle', 'person'),
('IATDD', 'group', 'Anastassis Spiliadis', 'person'),
('IATDD', 'group', 'Anna Hutchinton', 'person'),

('YouthTransCriticalProfessionals', 'defunct', 'Lisa Littman', 'person'),
('YouthTransCriticalProfessionals', 'defunct', 'Lisa Marchiano', 'person'),

('Autogynephilia', 'pseudoscientific theory', 'Ray Blanchard', 'person'),
('Autogynephilia', 'pseudoscientific theory', 'Michael Bailey', 'person'),

('Kenneth Zucker', 'person', 'Richard Green', 'person'),
('Kenneth Zucker', 'person', 'Robert Spitzer', 'person'),
('Kenneth Zucker', 'person', 'Richard Green', 'person'),
('Kenneth Zucker', 'person', 'James Cantor', 'person'),
('Kenneth Zucker', 'person', 'John Money', 'person'),
('Kenneth Zucker', 'person', 'Susan Bradley', 'person');